DROP TABLE IF EXISTS MEDICOS;
DROP TABLE IF EXISTS PACIENTES;
DROP TABLE IF EXISTS ENFERMEROS;
DROP TABLE IF EXISTS PERSONAS;


CREATE TABLE IF NOT EXISTS PERSONAS
(id INT auto_increment primary key,
atributoPersona VARCHAR(20) NOT NULL,
nombre VARCHAR(50) NOT NULL,
dni VARCHAR(10) NOT NULL,
direccion VARCHAR(50) NOT NULL,
nroPuerta INT NOT NULL,
cp INT NOT NULL,
telefono INT NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENFERMEROS
(
id INT auto_increment primary key,
personaId INT NOT NULL,
FOREIGN KEY (personaId) REFERENCES PERSONAS(id)
);

CREATE TABLE IF NOT EXISTS PACIENTES
(
id INT auto_increment primary key,
personaId INT NOT NULL,
FOREIGN KEY (personaId) REFERENCES PERSONAS(id)
);

CREATE TABLE IF NOT EXISTS MEDICOS
(
id INT auto_increment primary key,
personaId INT NOT NULL,
FOREIGN KEY (personaId) REFERENCES PERSONAS(id)
);

